-- 事件智能分派记录表
CREATE TABLE IF NOT EXISTS `event_dispatch_record` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `event_id` BIGINT NOT NULL COMMENT '事件ID',
    `recommended_dept_code` VARCHAR(64) DEFAULT NULL COMMENT '推荐部门编码',
    `recommended_dept_name` VARCHAR(128) DEFAULT NULL COMMENT '推荐部门名称',
    `confidence` DECIMAL(5,4) DEFAULT NULL COMMENT '分类置信度(0-1)',
    `auto_dispatch` TINYINT DEFAULT 0 COMMENT '是否自动分派(0否1是)',
    `dispatch_method` VARCHAR(32) DEFAULT NULL COMMENT '分类方法(rule/model/hybrid/fallback)',
    `actual_dept_code` VARCHAR(64) DEFAULT NULL COMMENT '实际分派部门编码',
    `actual_dept_name` VARCHAR(128) DEFAULT NULL COMMENT '实际分派部门名称',
    `status` VARCHAR(32) DEFAULT 'RECOMMENDED' COMMENT '状态(RECOMMENDED/AUTO_DISPATCHED/ADOPTED/REJECTED)',
    `adopted` TINYINT DEFAULT 0 COMMENT '是否被采纳(0否1是)',
    `feedback` VARCHAR(500) DEFAULT NULL COMMENT '反馈意见',
    `model_scores` TEXT DEFAULT NULL COMMENT '模型各分类得分JSON',
    `created_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除(0未删除1已删除)',
    PRIMARY KEY (`id`),
    KEY `idx_event_id` (`event_id`),
    KEY `idx_status` (`status`),
    KEY `idx_adopted` (`adopted`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件智能分派记录';
