"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const components_1 = require("@tarojs/components");
const classnames_1 = require("classnames");
const index_module_scss_1 = require("./index.module.scss");
const SyncProgress = ({ progress, showCancel = true, onCancel }) => {
    const percent = progress.total > 0
        ? Math.round(((progress.completed + progress.failed) / progress.total) * 100)
        : 0;
    return ((0, jsx_runtime_1.jsxs)(components_1.View, { className: index_module_scss_1.default.syncProgress, children: [(0, jsx_runtime_1.jsxs)(components_1.View, { className: index_module_scss_1.default.progressHeader, children: [(0, jsx_runtime_1.jsxs)(components_1.View, { className: index_module_scss_1.default.progressInfo, children: [(0, jsx_runtime_1.jsx)(components_1.Text, { className: index_module_scss_1.default.progressTitle, children: "\u6B63\u5728\u540C\u6B65" }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: index_module_scss_1.default.progressCount, children: [progress.completed + progress.failed, " / ", progress.total] })] }), showCancel && ((0, jsx_runtime_1.jsx)(components_1.View, { className: index_module_scss_1.default.cancelBtn, onClick: onCancel, children: (0, jsx_runtime_1.jsx)(components_1.Text, { className: index_module_scss_1.default.cancelText, children: "\u53D6\u6D88" }) }))] }), (0, jsx_runtime_1.jsx)(components_1.View, { className: index_module_scss_1.default.progressBarContainer, children: (0, jsx_runtime_1.jsx)(components_1.Progress, { percent: percent, strokeWidth: 8, activeColor: "#165DFF", backgroundColor: "#E5E6EB", active: true }) }), (0, jsx_runtime_1.jsxs)(components_1.View, { className: index_module_scss_1.default.progressDetails, children: [(0, jsx_runtime_1.jsxs)(components_1.View, { className: index_module_scss_1.default.detailItem, children: [(0, jsx_runtime_1.jsx)(components_1.View, { className: (0, classnames_1.default)(index_module_scss_1.default.dot, index_module_scss_1.default.successDot) }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: index_module_scss_1.default.detailText, children: ["\u6210\u529F ", progress.completed] })] }), progress.failed > 0 && ((0, jsx_runtime_1.jsxs)(components_1.View, { className: index_module_scss_1.default.detailItem, children: [(0, jsx_runtime_1.jsx)(components_1.View, { className: (0, classnames_1.default)(index_module_scss_1.default.dot, index_module_scss_1.default.failedDot) }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: index_module_scss_1.default.detailText, children: ["\u5931\u8D25 ", progress.failed] })] })), (0, jsx_runtime_1.jsxs)(components_1.View, { className: index_module_scss_1.default.detailItem, children: [(0, jsx_runtime_1.jsx)(components_1.View, { className: (0, classnames_1.default)(index_module_scss_1.default.dot, index_module_scss_1.default.pendingDot) }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: index_module_scss_1.default.detailText, children: ["\u5F85\u5904\u7406 ", progress.total - progress.completed - progress.failed] })] })] }), progress.currentEvent && ((0, jsx_runtime_1.jsx)(components_1.View, { className: index_module_scss_1.default.currentEvent, children: (0, jsx_runtime_1.jsxs)(components_1.Text, { className: index_module_scss_1.default.currentEventText, children: ["\u5F53\u524D: ", progress.currentEvent.title] }) }))] }));
};
exports.default = SyncProgress;
//# sourceMappingURL=index.js.map